{{- if .Values.image.imageVectorOverwrite }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "name" . }}-imagevector-overwrite
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels" . | indent 4 }}
data:
  images_overwrite.yaml: |
{{ .Values.image.imageVectorOverwrite | indent 4 }}
{{- end }}
