apiVersion: v1
kind: ServiceAccount
metadata:
  name: gardener-extension-runtime-gvisor
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gardener-extension-runtime-gvisor
    helm.sh/chart: gardener-extension-runtime-gvisor
    app.kubernetes.io/instance: {{ .Release.Name }}
